FRIEND = 1
PLAYER = 1
ENNEMY = -1
NEUTRAL = 0
NEUTRAL_2 = 2

NB_CYBORG_INC = 10
DELTA_CONQUER = 1
FIRST_EXPLORATION_DELTA = 5

MAX_BOMB_DISTANCE = 5
MIN_DEFENSE_TO_SEND_BOMB = 5

COUNT_INCREASE = 0

MIN_FACTORY_CONSIDERED = 6
MAX_DISTANCE_CONSIDERED = 4
NB_PREDICTED_TURN = 3
NB_PREDICTED_TURN_BOMB = 5